####
# Opencast Stand-alone Video Editor
##

# !!! When deployed, this file is publicly accessibly

####
# General Settings
##

# Id of the event that the editor should open by default.
# This is very useful as demo, but has no purpose otherwise.
# Type: string | undefined
# Default: undefined
id = 'https://develop.opencast.org'


####
# Connection to Opencast
##

[opencast]

# URL of the opencast server to connect to.
# The default will work just fine if integrated in Opencast.
# Type: URL
# Default: Current server
url = 'http://localhost:8080'

# Username, used for HTTP basic authentication against Opencast.
# Not defining this will work just fine if integrated in Opencast.
# Type: string | undefined
# Default: undefined
name = "admin"

# Username, used for HTTP basic authentication against Opencast.
# Not defining this will work just fine if integrated in Opencast.
# Type: string | undefined
# Default: undefined
password = "opencast"


####
# Metadata
##

[metadata]
# If the metadata editor appears in the main menu
# Type: boolean
# Default: true
#show = true

## Metadata display configuration
## Override various settings for how metadata catalogs and fields will be
## displayed in the editor. Configuration happens for each catalog separately.
##
## Configuration options for fields:
##
##   show (boolean): Show or hide fields
##   readonly (boolean): Mark fields as readonly
##
## Default behavior:
##
## - The default settings are based on Opencast's admin interface configuration
## - If catalogs are not specified, all of its fields will be displayed
## - If a catalog is specified but empty, it will not be displayed
##
## Example:
##
# # This is the default catalog
# [metadata.configureFields."EVENTS.EVENTS.DETAILS.CATALOG.EPISODE"]
# title = {show = true, readonly = false}
# subject = {show = false}
# description = {readonly = true}
#
# # This catalog is specified but empty, and as such will not be displayed
# [metadata.configureFields."NameOfAnExtendedMetadataCatalog"]


####
# Track Selection
##

[trackSelection]

# If the track selection appears in the main menu
# Type: boolean
# Default: true
#show = true


####
# Thumbnail Selection
##

[thumbnail]

# If the thumbnail editor appears in the main menu
# Warning: This interface is unfinished
# Type: boolean
# Default: false
#show = false
