####
# Opencast Stand-alone Video Editor
##

# !!! When deployed, this file is publicly accessibly

####
# General Settings
##

# Id of the event that the editor should open by default.
# This is very useful as demo, but has no purpose otherwise.
# Type: string | undefined
# Default: undefined
# id = '63af7c8b-faf9-4b14-be58-07ab268db5fe'
id = '3569e20d-7181-4a60-9816-43fd887063b3'


####
# Connection to Opencast
##

[opencast]

# URL of the opencast server to connect to.
# The default will work just fine if integrated in Opencast.
# Type: URL
# Default: Current server
url = 'http://localhost:8080'



# Username, used for HTTP basic authentication against Opencast.
# Not defining this will work just fine if integrated in Opencast.
# Type: string | undefined
# Default: undefined
name = "admin"

# Username, used for HTTP basic authentication against Opencast.
# Not defining this will work just fine if integrated in Opencast.
# Type: string | undefined
# Default: undefined
password = "opencast"


####
# Metadata
##

[metadata]
# If the metadata editor appears in the main menu
# Type: boolean
# Default: true
#show = true

## Metadata display configuration
## Override various settings for how metadata catalogs and fields will be
## displayed in the editor. Configuration happens for each catalog separately.
##
## Configuration options for fields:
##
##   show (boolean): Show or hide fields
##   readonly (boolean): Mark fields as readonly
##
## Default behavior:
##
## - The default settings are based on Opencast's admin interface configuration
## - If catalogs are not specified, all of its fields will be displayed
## - If a catalog is specified but empty, it will not be displayed
##
## Example:
##
# # This is the default catalog
# [metadata.configureFields."EVENTS.EVENTS.DETAILS.CATALOG.EPISODE"]
# title = {show = true, readonly = false}
# subject = {show = false}
# description = {readonly = true}
#
# # This catalog is specified but empty, and as such will not be displayed
# [metadata.configureFields."NameOfAnExtendedMetadataCatalog"]


####
# Track Selection
##

[trackSelection]

# If the track selection appears in the main menu
# Type: boolean
# Default: true
#show = true

####
# Subtitles
##

[subtitles]

# If the subtitle editor appears in the main menu
# Type: boolean
# Default: true
#show = true

# The main flavor of the subtitle tracks in Opencast
# No other tracks should have the same main flavor as subtitle tracks
# Type: string
# Default: "captions"
# TODO: Allow multiple main flavors?
mainFlavor = "captions"

## A list of languages for which subtitles can be created
#
# TODO: Figure out a real world example based on actual Opencast information
# TODO: Comment out example
# Example:
[subtitles.languages]
"source+de" = "Deutsch"
"source+de_Irgendwas" = "Deutsch (Geh√∂rlos)"
"source+en" = "English"
"source+en_US" = "English (US)"
"source+en_GB" = "English (GB)"
"source+br" = "Donaudampfschifffahrtsgesellschaft"
"source+de_2" = "Deutsch 2"
"source+de_3" = "Deutsch 3"
"source+de_4" = "Deutsch 4"
"source+de_5" = "Deutsch 5"
"ü¶ù" = "ü¶ù"

####
# Thumbnail Selection
##

[thumbnail]

# If the thumbnail editor appears in the main menu
# Warning: This interface is unfinished
# Type: boolean
# Default: false
#show = false
