####
# Opencast Stand-alone Video Editor
##

# This file contains configuration meant for development and demonstration.
# New features should be enabled in here to make testing easier.

# âš ï¸  Please do not use this for production deployments.


# Pick a default event identifier which should be on develop.opencast.org
id = 'ID-dual-stream-demo'

[opencast]
# Connect to develop.opencast.org and use the default demo user
url = 'https://develop.opencast.org'
name = "admin"
password = "opencast"


[metadata]
show = true

[trackSelection]
show = true

[subtitles]
show = true
mainFlavor = "captions"

[subtitles.languages]
"captions/source+de" = "Deutsch"
"captions/source+en" = "English"
"captions/source+es" = "Spanish"
"captions/source" = "Generic"

[subtitles.icons]
"captions/source+de" = "ğŸ‡©ğŸ‡ª"
"captions/source+en" = "ğŸ‡ºğŸ‡¸"
"captions/source+es" = "ğŸ‡ªğŸ‡¸"

[thumbnail]
show = true
