name: Playwright UI-Test

on:
  pull_request:
    branches:
      - main

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    
    - name: Install Node Dependency
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - name: npm install dependencies
      run: npx playwright install-deps

    - name: Install npm install -D @playwright/test
      run: npm install -D @playwright/test

    - name: npm run playwright-test
      run: npx playwright test --config=playwright.config.ts